sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456  # 修改为自己的数据库密码
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t5pA1xM8C9AV2t6kb5t
    # TODO: 替换为自己的阿里云 AccessKeyId
    access-key-secret: rW0a2btUUtCNXaAHRrVyzBJOryPRLz
    # TODO: 替换为自己的阿里云 AccessKeySecret
    bucket-name: java-aiczd  # TODO: 替换为自己的阿里云 OSS Bucket 名称
  redis:
    host: localhost
    port: 6379
    database: 0  # 如有其他 Redis 配置请修改
  wechat:
    appid: wx3f3f0e917148b693
    secret: 0ec30a213e6de9067dd705d8ee2ec89e
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl:  http://303d6319.r6.cpolar.cn/notify/paySuccess
    refundNotifyUrl:  http://303d6319.r6.cpolar.cn/notify/refundSuccess
    testMode: true
